# Generated by Django 4.2 on 2023-04-21 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spawns', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Npc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('pv', models.CharField(max_length=200)),
                ('ataque', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('pe', models.CharField(max_length=200)),
                ('ataque', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
                ('hostilidad', models.CharField(max_length=200)),
                ('personaje', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestorapp.personaje')),
            ],
        ),
        migrations.CreateModel(
            name='Dialogos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('npc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestorapp.personaje')),
            ],
        ),
    ]
