# Generated by Django 4.2 on 2023-04-21 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camino',
            name='dificultad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
